### ISSUE TITLE
Is off platform sending dealer id and account id

### ISSUE THREAD

**Issue by jesseroberts927** [cassler/CruiseControl-for-DR#24]
Looking for an easy way to determine if an off platform website provider is passing dealerid, accountid or both in the CADigitalRetailing object.

**Comment by cassler** [comment]
@jesseroberts927 - you can try out the raw results of this validation by pasting the code found here into your browser console: https://github.com/cassler/CruiseControl-for-DR/blob/363d508f5f42b6b60882d1a9a073bbeb12e8df10/lib/_test_CADigitalRetailObject.js . Once we can confirm that it returns good data, we can bootstrap a UI.
