### ISSUE TITLE
Pixel QA for GM DDS

### ISSUE THREAD

**Issue by colleenfiske** [cassler/CruiseControl-for-DR#7]
Darin - Hoping to create a bookmarklet that allows a team member to confirm if a GM off-platform website has the pixel Pix-gm.min.js already active on the website. Thank you!

javascript:(function(){ let str; if (document.querySelectorAll('script[src="//assets.prod.analytics.dealer.com/pixall/pix-gm.min.js"]').length == 1) { str = 'GOOD JOB,\nThey have the correct script.'; } else { str = 'Nope, sorry' } window.alert(str) })();

**Comment by cassler** [comment]
Note: Look to roll this in to CADRO Test and make single off-platform check.
